# UI/UX Accessibility

This repository is for the documenting of UI and UX accessibility
patterns that can be used by developers, testers, and auditors for
determining the accessibility of an operating system desktop or
"shell", programs running atop a desktop, web pages, or other frontend
experience.

* Contents [in progress]

- [[./bios.org][BIOS and UEFI]]
- [[./operating-systems.org][Operating Systems]]
- [[./desktop-environments.org][Desktop Environments]]
- [[./applications.org][Applications]]
- [[./web.org][Webpages]]
- [[./documents.org][Documents]]

* Contributing and Contacting

This repository will not reach its full potential without
contributions from other people with disabilites, programmers, and
other invested people. So, you can either fork the repository, make
changes, and send pull requests, ask to be added as a contributor (if
you plan on contributing heavily), or send requested changes via
e-mail or other communication channels. Just please send the changes
through a channel that supports long, multi-line messages.

My contact info is below:

- Email :: r.d.t.prater@gmail.com
- Twitter :: @devinprater
- Mastodon :: devinprater@dragonscave.space

