#+title: Website Accessibility

A website, here, is a collection of pages, made of HTML, CSS, and
JavaScript, presented usually over the Internet to users' web
browsers.

** Prime Directive

The prime directive is to communicate with users. The user will
generally know what they would like rather than what wouldn't help or
even hinder their experience. Some users may have different ideas of
what is "accessible" versus other users. In cases like this, you'll
either need to choose between the two ideas, or give the users a
choice between the two (preferable). When it comes to accessibility,
choice is never a bad thing. Your users will thank you for giving them
something that makes their own experience enjoyable, productive, or
both.

** Totally Blind Users

This section will concern users who have either only light perception
or cannot see anything at all. People who have limited vision will be
addressed in another section.

*** HTML

Use HTML for content, not layout or looks. Tables should only be for
the display of data, not for layout of regular information. If you
want information to be in columns, do that using CSS.

*** Use Headings and Landmarks

Headings are for sectioning out your page. Try to only have one
heading at level one, as the title of the page, article, or main
content. This allows blind users who use only headings to find the
main content of a site more quickly, and for those who use landmarks
to do the same thing with the Main landmark. Keep in mind, though,
that many screen readers only allow users to move from landmark to
landmark, so if you've got a Navigation landmark for your navigation
bar, then an Aside landmark for some complementary content, it'll take
more key presses to find the Main landmark than it will the heading at
level one.

Landmarks are for more screen reader specific navigation. A main
landmark denotes the main section of the page. Landmarks are for
dividing your page into regions for faster navigation. They can be
very helpful in news sites, where the article landmark allows the user
to move from one article to the next, if the screen reader supports the
movement from one Article to the next.

*** Labeling Widgets

Within form controls, like buttons, edit fields, check boxes, and
radio buttons, it is important to give them textual labels using the
label tag. Screen readers will read this to the user.

Be sure to label widgets simply and briefly. It's better to label a
button "close" than it is to label it "A green close button on a blue
background." Do not add the widget's roll to the label either, as the
browser will know what kind of widget it is, and will communicate that
to the screen reader.

*** Don't Use ARIA

You may have heard of ARIA, which allows a web developer to control a
lot of what a screen reader says and does on a site. However,
configuring ARIA can be brittle and painful, requiring a lot of manual
intervention when something breaks.  It is much easier to instead use
simple, pure HTML, which screen readers and browsers are already good
at understanding.

*** Label Images

Images must contain an "alt" attribute with a description of the
image.  It doesn't matter if your descriptions are exquisitely vivid
and detailed; what matters is that you get the point across. For
example, "An orange kitten curled up on a windowsill in a sunbeam" is
good enough for most cases.

*** Language Changes

If there is a widget, like a paragraph, in a different languages, use
the "lang" attribute to tell the screen reader which language to speak
in. This helps in language-learning sites, or even social networks
which allow multi-lingual posts.

* Resources

- [[https://adrianroselli.com/2021/06/using-css-to-enforce-accessibility.html][Using
  CSS to enforce Accessibility]]
- [[https://webaim.org/projects/screenreadersurvey8/][WebAIM Screen
  reader survey]]
- [[https://levelup.gitconnected.com/wcag-2-1-simplified-how-to-make-your-website-accessible-1cfadd03d20d][WCAG 2.1, Simplified: How to Make Your Website Accessible]]
- [[https://www.w3.org/WAI/people-use-web/user-stories/][Web
  Accessibility Initiative: Story of web users]]
- [[https://wave.webaim.org][WebAIm Accessibility checker]]
